### ISSUE TITLE
I could not use MaterialModule  

### ISSUE THREAD

**Issue by luke-emmental** [thymikee/jest-preset-angular#52]
```
 console.warn node_modules/@angular/material/bundles/material.umd.js:146
    Current document does not have a doctype. This may cause some Angular Material components not to behave as expected.

  console.warn node_modules/@angular/material/bundles/material.umd.js:159
    Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming


ReferenceError: CSS is not defined
```

What should i do?

**Comment by thymikee** [comment]
You're probably hitting this: https://github.com/facebook/jest/issues/3299
I'll be implementing new testEnvironment for this preset, so I can keep that in mind and add support for doctype. If you don't have time, you can create your own testEnvironment (copy-paste [existing one](https://github.com/facebook/jest/blob/master/packages/jest-environment-jsdom/src/index.js) and adjust it as I commented in mentioned issue)

Use it in your jest config like:
```json
{
  "testEnvironment": "path/to/your/custom_test_env.js"
}
```

**Comment by luke-emmental** [comment]
thanks reply! It is harder than I thought. I'm trying

**Comment by thymikee** [comment]
Yea it's not a regular thing you do with Jest, but it's definitely possible to adjust :)

**Comment by luke-emmental** [comment]
vmDom.js
`const _util = require('jest-util');
const FakeTimers = _util.FakeTimers, installCommonGlobals = _util.installCommonGlobals;
const mock = require('jest-mock');
const jsdom = require('jsdom');
// const evalScript = require('jsdom/lib/old-api').evalVMScript;
const path = require('path');
const fs = require('fs');
const process = require('process');
// console.log(path.parse(__dirname).dir);

const maincss = fs.readFileSync(path.normalize(`${path.parse(__dirname).dir}/node_modules/@angular/material/prebuilt-themes/indigo-pink.css`), 'utf8');
const vm = require('vm');
// const createContext = require('vm').createContext;

class JSDOMEnvironment {


  constructor(config) {
    // lazy require
    this.browser = new jsdom.JSDOM(`<!DOCTYPE html><head></head><body></body><html>`, {
      features : {
        FetchExternalResources : ['script', 'style', 'link'],
        QuerySelector : true
      },
      url: config.testURL
    });

    const _global = (this.global = this.browser.window);

    // Node's error-message stack size is limited at 10, but it's pretty useful
    // to see more than that when a test fails.
    const document = _global.document;
    let head = document.getElementsByTagName('head')[0];
    let style = document.createElement("style");
    style.type = 'text/css';
    style.innerHTML = maincss;
    head.appendChild(style);
    console.log(document);
    // this.global.Error  = Object.assign({}, global.Error);
    // console.log(Object.assign({}, process));
    // this.global.process = Object.assign({}, process);
    // this.global.Error.stackTraceLimit = 100;
    installCommonGlobals(_global, config.globals);
    //
    this.moduleMocker = new mock.ModuleMocker(_global);
    this.fakeTimers = new FakeTimers(_global, this.moduleMocker, config);
  }

  dispose() {
    if (this.fakeTimers) {
      this.fakeTimers.dispose();
    }
    if (this.global) {
      this.global.close();
    }
    this.global = null;
    this.browser = null;
    this.fakeTimers = null;
  }
  //
  runScript(script) {
    // console.log(script);
    if (this.global) {

      return script.runInContext(vm.createContext(this.global));
    }
    return null;
  }
}
// new JSDOMEnvironment({testURL: 'https://github.com/letsrock-today/mock-local-storage'});

module.exports = JSDOMEnvironment;`

**Comment by thymikee** [comment]
See how it's done here: https://github.com/Micromeritics/jest-environment-jsdom-11.0.0. You can also send them a PR and use it.

**Comment by luke-emmental** [comment]
thanks @thymikee

**Comment by michahell** [comment]
Also hitting this, after first having hit the bug with merging `moduleNameMapper` from a preset + `jest.config` :( It seems that JEST plug and play is not that easy after all :(

**Comment by thymikee** [comment]
@luke-emmental can you send a PR to example in  this repo with usage if Material module, so I can test new environment?

**Comment by michahell** [comment]
Hmm. maybe there is a way to mock material components, seems like the material design guys would do that to test their own nested components 🤔

**Comment by ollwenjones** [comment]
Same deal here.

**Comment by ollwenjones** [comment]
adding
```javascript
Object.defineProperty(window, 'CSS', {value: mock()});
```
to my `jestGlobalMocks.ts` seems to have cleared up the `CSS is not defined` issue for me.

**Comment by michahell** [comment]
nice @ollwenjones ! I can at least get JEST to pass a basic component spec using material design icons. I do still get the following warnings / errors:

```
console.warn node_modules/@angular/material/bundles/material.umd.js:146
    Current document does not have a doctype. This may cause some Angular Material components not to behave as expected.

  console.warn node_modules/@angular/material/bundles/material.umd.js:159
    Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming

  console.log node_modules/@angular/material/bundles/material.umd.js:13754
    Loading icon set URL: [object Object] failed: SyntaxError

  console.log node_modules/@angular/material/bundles/material.umd.js:14108
    Error retrieving icon: Unable to find icon with the name "security-outline"
```

which are probably still related to the Jsdom document type setting

**Comment by zack9433** [comment]
I add some mock

```javascript
Object.defineProperty(document, 'doctype', {
  value: '<!DOCTYPE html>'
});
Object.defineProperty(window, 'getComputedStyle', {
  value: () => {
    return {
      display: 'none',
      appearance: ['-webkit-appearance']
    };
  }
});
```
and warning messages 
```
console.warn node_modules/@angular/material/bundles/material.umd.js:146
    Current document does not have a doctype. This may cause some Angular Material components not to behave as expected.

  console.warn node_modules/@angular/material/bundles/material.umd.js:159
    Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming

```
are gone

**Comment by thymikee** [comment]
@zack9433 nice! Thank you for sharing :)

**Comment by thymikee** [comment]
Would you mind adding PR to the example, so it's there by default? 
https://github.com/thymikee/jest-preset-angular/blob/master/example/src/jestGlobalMocks.ts

**Comment by michahell** [comment]
Awesome! going to try that right now, thanks for sharing @zack9433 !

**Comment by michahell** [comment]
But I think this has the same effect as using the 
`{provide: MATERIAL_SANITY_CHECKS, useValue: false},` provider in your
`TestBed.configureTestingModule()` setup, no ?

**Comment by zack9433** [comment]
@thymikee sorry for lately reply. I already created a PR for this issue.
@michahell I think you can try to load a fake icon like [this](https://github.com/angular/material2/blob/master/src/lib/icon/icon.spec.ts#L74)

**Comment by thymikee** [comment]
Fixed with https://github.com/thymikee/jest-preset-angular/pull/61

**Comment by denniske** [comment]
I think the following is still missing in `jestGlobalMocks.ts`:

`Object.defineProperty(window, 'CSS', {value: mock()});`
