### ISSUE TITLE
fakeAsync doesn't work

### ISSUE THREAD

**Issue by vvasabi** [thymikee/jest-preset-angular#65]
Steps to reproduce:
1. Clone [this repo](https://github.com/vvasabi/jest-angular-fakeasync).
2. Run `yarn` and `yarn jest` and note that the fakeAsync test fails

Note that `yarn test`, which uses Karma, passes.

**Comment by correasebastian** [comment]
any update here? any clue?

**Comment by thymikee** [comment]
Haven't tested this yet, but I remember `fakeAsync` worked for me.

**Comment by correasebastian** [comment]
@thymikee  fakeAsync is doing its job flushing promises, but looks like is having hard time flushing timers, not sure why. but this is an example too

https://github.com/correasebastian/angular4-jest.git

**Comment by Waldo000000** [comment]
Alternative repro steps @thymikee:

1. Clone the example project (https://github.com/thymikee/jest-preset-angular/tree/master/example)
2. Add the following spec to the project (copied directly from https://angular.io/api/core/testing/fakeAsync):
```
describe('this test', () => {
  it('looks async but is synchronous', <any>fakeAsync((): void => {
       let flag = false;
       setTimeout(() => { flag = true; }, 100);
       expect(flag).toBe(false);
       tick(50);
       expect(flag).toBe(false);
       tick(50);
       expect(flag).toBe(true);
     }));
});
```
3. Upgrade zone.js: `yarn upgrade zone.js@0.8.11` (same behavior for latest zone.js version, i.e. 0.8.17)
4. `yarn test` -- fails

Note that the same test (with the same dependencies) _passes_ when using webpack + karma + Chrome headless.

**Comment by alonewarrior** [comment]
I'm having this same issue, my tests are failing because I'm requiring the use of a setTimeout to get certain behavior in the UI and these behaviors aren't being picked up by Jest until after the test has failed.

**Comment by thymikee** [comment]
I won't be able to verify it in following days, would appreciate some help on this in the meantime.

**Comment by thymikee** [comment]
Thanks @Waldo000000, I've confirmed it works with zone 0.8.10, but breaks since 0.8.11. I've also been able to track the change, which I think is a bug, but who knows.

I've asked about that in the relevant PR which introduced the change. Any help on this appreciated.


**Temporary solution**: lock down zone.js to 0.8.10

**Comment by thymikee** [comment]
I have a fix for that, which involves using newer version of `jsdom`, which means custom Jest environment. So I'll release it as a major version, since we'll drop Node 4 support (which will be dropped in Jest in couple of months anyway because it reaches its EOL).

**Comment by thymikee** [comment]
Hey folks, I've just released `v4.0.0-alpha.1`, can you give it a try with the `zone.js` >=0.8.11?

**Comment by vvasabi** [comment]
The fakeAsync test now passes in my test repo. Thank you very much! 🎉

**Comment by tkstang** [comment]
I'm using jest-preset-angular@5.0 and zone@0.8.2 and fakeAsync still fails for me

**Comment by AhnpGit** [comment]
@tkstang I'm using jest-preset-angualr@5.0 and zone@0.8.19, fakeAsync works fine for me. Can you try updating zone ?

**Comment by tkstang** [comment]
0.8.20 is more up to date than 0.8.19 is it not?

**Comment by AhnpGit** [comment]
I haven't tried 0.8.20 yet but fakeAsync works for me at 0.8.19. Perhaps you can try 0.8.19 1st to see

**Comment by maxime1992** [comment]
Hi, I'm currently facing the exact same issue with `"zone.js": "0.8.29"` and `"jest": "24.1.0"`, `"jest-preset-angular": "6.0.2"`. Any idea how to solve that? 

My test is broken and then it ends up with 

```
Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
```
